# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 ProtocolWarden
"""Shared RepoGraph public API."""

from .errors import RepoGraphConfigError
from .ontology import (
    DisclosureMode,
    EntityKind,
    LOCAL_ANNOTATION_FIELDS,
    ManifestHeader,
    ManifestKind,
    OwnerKind,
    PlatformPlane,
    RepoIdentity,
    RepoKind,
    RepoNode,
    RepoVisibility,
    Source,
    Visibility,
)
from .projection import (
    BoundaryDisclosureArtifact,
    DEFAULT_PROJECTION_PROFILE_RULES,
    ProjectionBehavior,
    ProjectionProfile,
    ProjectionProfileKind,
    ProjectionProfileRules,
    PublicGraphProjection,
    build_boundary_artifact,
    build_public_projection,
    build_projection_profile,
    can_project_node,
    can_project_relationship,
    default_projection_behavior_for_visibility,
    public_name,
    to_public_manifest_dict,
)
from .diff import GraphChange, GraphDiffResult, RepoGraphDiff
from .schema import (
    BreakingChangePolicy,
    CompatibilityPolicy,
    CURRENT_SCHEMA_VERSIONS,
    SchemaKind,
    SchemaVersion,
    classify_schema_change,
    compute_artifact_hash,
    ensure_supported_schema_version,
    is_supported_schema_version,
    schema_version_for,
    validate_boundary_artifact_payload,
    validate_schema_document,
)
from .topology import (
    EdgeCategory,
    EdgeKind,
    GraphEdge,
    OntologyRelationship,
    OntologyRelationshipKind,
    RELATIONSHIP_EDGE_CATEGORIES,
    RepoEdge,
    RepoEdgeType,
    RepoGraph,
)

__all__ = [
    "BoundaryDisclosureArtifact",
    "BreakingChangePolicy",
    "CompatibilityPolicy",
    "CURRENT_SCHEMA_VERSIONS",
    "DisclosureMode",
    "EdgeCategory",
    "EdgeKind",
    "EntityKind",
    "GraphChange",
    "GraphDiffResult",
    "GraphEdge",
    "LOCAL_ANNOTATION_FIELDS",
    "ManifestHeader",
    "ManifestKind",
    "OntologyRelationship",
    "OntologyRelationshipKind",
    "OwnerKind",
    "PlatformPlane",
    "ProjectionBehavior",
    "ProjectionProfile",
    "ProjectionProfileKind",
    "ProjectionProfileRules",
    "PublicGraphProjection",
    "RELATIONSHIP_EDGE_CATEGORIES",
    "RepoEdge",
    "RepoEdgeType",
    "RepoGraphDiff",
    "RepoGraph",
    "RepoGraphConfigError",
    "RepoIdentity",
    "RepoKind",
    "RepoNode",
    "RepoVisibility",
    "Source",
    "SchemaKind",
    "SchemaVersion",
    "Visibility",
    "build_projection_profile",
    "build_boundary_artifact",
    "build_public_projection",
    "classify_schema_change",
    "compute_artifact_hash",
    "can_project_node",
    "can_project_relationship",
    "ensure_supported_schema_version",
    "default_projection_behavior_for_visibility",
    "is_supported_schema_version",
    "public_name",
    "schema_version_for",
    "DEFAULT_PROJECTION_PROFILE_RULES",
    "validate_boundary_artifact_payload",
    "validate_schema_document",
    "to_public_manifest_dict",
]
