# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 ProtocolWarden
"""Shared RepoGraph public API."""

from .errors import RepoGraphConfigError
from .ontology import (
    DisclosureMode,
    EntityKind,
    LOCAL_ANNOTATION_FIELDS,
    ManifestHeader,
    ManifestKind,
    OwnerKind,
    PlatformPlane,
    RepoIdentity,
    RepoKind,
    RepoNode,
    RepoVisibility,
    Source,
    Visibility,
)
from .projection import (
    BoundaryDisclosureArtifact,
    ProjectionBehavior,
    ProjectionProfile,
    PublicGraphProjection,
    build_boundary_artifact,
    build_public_projection,
    can_project_node,
    can_project_relationship,
    default_projection_behavior_for_visibility,
    public_name,
    to_public_manifest_dict,
)
from .topology import (
    EdgeCategory,
    EdgeKind,
    GraphEdge,
    OntologyRelationship,
    OntologyRelationshipKind,
    RELATIONSHIP_EDGE_CATEGORIES,
    RepoEdge,
    RepoEdgeType,
    RepoGraph,
)

__all__ = [
    "BoundaryDisclosureArtifact",
    "DisclosureMode",
    "EdgeCategory",
    "EdgeKind",
    "EntityKind",
    "GraphEdge",
    "LOCAL_ANNOTATION_FIELDS",
    "ManifestHeader",
    "ManifestKind",
    "OntologyRelationship",
    "OntologyRelationshipKind",
    "OwnerKind",
    "PlatformPlane",
    "ProjectionBehavior",
    "ProjectionProfile",
    "PublicGraphProjection",
    "RELATIONSHIP_EDGE_CATEGORIES",
    "RepoEdge",
    "RepoEdgeType",
    "RepoGraph",
    "RepoGraphConfigError",
    "RepoIdentity",
    "RepoKind",
    "RepoNode",
    "RepoVisibility",
    "Source",
    "Visibility",
    "build_boundary_artifact",
    "build_public_projection",
    "can_project_node",
    "can_project_relationship",
    "default_projection_behavior_for_visibility",
    "public_name",
    "to_public_manifest_dict",
]
